# Site settings
title: Blog 
name: Aaron Wu # your name
name_zh: 吴文锋 # your name
email: aaronwwf@qq.com # your email address
description: >
    Where I post my thoughts. # this means to ignore newlines until "baseurl:"
description_zh: >
    记录我想法的地方。 
baseurl: "/blog" # the subpath of your site, e.g. /blog
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aaronwwf.com" # the base hostname & protocol for your site
twitter_username: aaronwuw # your Github username
github_username: aaronwwf # your Github username
disqus_username: aaronwwf-com # your disqus username

#google-analytics: UA-75034651-1 # add it if you have one

#skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
